services:
  - type: web
    name: orik-backend
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python manage.py migrate && python manage.py seed_content --reset && gunicorn config.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.1
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
