# Generated by Django 5.0.14 on 2026-09-26 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiries', '0002_alter_enquiry_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text='Unique: a second sign-up updates the first.', max_length=254, unique=True)),
                ('is_active', models.BooleanField(default=True, help_text='Clear this instead of deleting when someone opts out.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=300)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
