# Generated by Django 5.0.14 on 2026-09-26 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enquiries', '0003_subscriber'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subscriber',
        ),
    ]
