# Generated by Django 5.0.14 on 2026-09-26 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_templates_and_industries_section'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterTopSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('left_heading', models.TextField(default='Business first, with personal support.', help_text='Line breaks are kept on wide screens.')),
                ('left_cta_label', models.CharField(default='Our process', max_length=60)),
                ('left_cta_href', models.CharField(default='/process', help_text='A path such as "/process".', max_length=120)),
                ('left_image', models.ImageField(blank=True, help_text='Leave blank to keep the built-in photo.', upload_to='footer-top/')),
                ('left_image_alt', models.CharField(blank=True, help_text='Required if you upload an image.', max_length=160)),
                ('right_eyebrow', models.CharField(default='Why ORIK Webcraft', help_text='The small line above the heading.', max_length=60)),
                ('right_heading', models.TextField(default='Responsive, modern websites\nthat grow with you.', help_text='Line breaks are kept on wide screens.')),
                ('right_cta_label', models.CharField(default='View our work', max_length=60)),
                ('right_cta_href', models.CharField(default='/work', max_length=120)),
                ('right_image', models.ImageField(blank=True, help_text='Leave blank to keep the built-in photo.', upload_to='footer-top/')),
                ('right_image_alt', models.CharField(blank=True, help_text='Required if you upload an image.', max_length=160)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'footer top',
                'verbose_name_plural': 'footer top',
            },
        ),
    ]
