# Generated by Django 5.0.14 on 2026-09-26 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_footer_top'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sociallink',
            name='href',
            field=models.URLField(blank=True, help_text='Full URL. For WhatsApp use https://wa.me/<number>. Blank links stay hidden on the site.'),
        ),
        migrations.AlterField(
            model_name='sociallink',
            name='platform',
            field=models.CharField(choices=[('whatsapp', 'WhatsApp'), ('instagram', 'Instagram'), ('facebook', 'Facebook'), ('linkedin', 'LinkedIn'), ('twitter', 'Twitter'), ('youtube', 'YouTube'), ('medium', 'Medium')], max_length=20, unique=True),
        ),
    ]
