# Generated by Django 5.0.14 on 2026-09-26 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0008_social_platforms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sociallink',
            name='platform',
            field=models.CharField(choices=[('whatsapp', 'WhatsApp'), ('instagram', 'Instagram'), ('facebook', 'Facebook'), ('linkedin', 'LinkedIn')], max_length=20, unique=True),
        ),
    ]
