# Generated by Django 5.0.14 on 2026-09-26 08:16

from django.db import migrations, models


# The three seeded cards, in the order they appear. Matching on order rather
# than title means a card renamed in the admin still gets the right icon.
ICONS_BY_ORDER = ["search-x", "history", "message-circle-off"]
DEFAULT_HIGHLIGHT = "social media page."


def fill(apps, schema_editor):
    Problem = apps.get_model("content", "Problem")
    for index, problem in enumerate(Problem.objects.order_by("order", "id")):
        if index < len(ICONS_BY_ORDER):
            problem.icon = ICONS_BY_ORDER[index]
            problem.save(update_fields=["icon"])

    YourIdeaSection = apps.get_model("content", "YourIdeaSection")
    for section in YourIdeaSection.objects.all():
        if not section.heading_highlight and DEFAULT_HIGHLIGHT in section.heading:
            section.heading_highlight = DEFAULT_HIGHLIGHT
            section.save(update_fields=["heading_highlight"])


def unfill(apps, schema_editor):
    """Nothing to undo: both columns are dropped when this is reversed."""


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0009_social_four_platforms'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='icon',
            field=models.CharField(choices=[('search-x', 'Not found in search'), ('history', 'Out of date'), ('message-circle-off', 'No way to get in touch'), ('monitor-x', 'Broken on phones'), ('hourglass', 'Slow to load'), ('triangle-alert', 'General warning')], default='triangle-alert', max_length=24),
        ),
        migrations.AddField(
            model_name='yourideasection',
            name='heading_highlight',
            field=models.CharField(blank=True, help_text='Words from the heading to mark in yellow, e.g. “social media page.” Leave blank for none.', max_length=80),
        ),
        migrations.RunPython(fill, unfill),
    ]
