# Generated by Django 5.0.14 on 2026-09-26 09:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0010_your_idea_highlight_and_problem_icons'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterBottomSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_label', models.CharField(default='Menu', help_text='Heading above the list of links.', max_length=40)),
                ('contact_label', models.CharField(default='Contact Us', max_length=40)),
                ('enquiry_label', models.CharField(default='Send us an enquiry', max_length=60)),
                ('enquiry_href', models.CharField(default='/contact', help_text='A path such as "/contact".', max_length=120)),
                ('copyright_note', models.CharField(default='All Rights Reserved.', help_text='Follows the year and the site name.', max_length=80)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'footer bottom',
                'verbose_name_plural': 'footer bottom',
            },
        ),
        migrations.AddField(
            model_name='sociallink',
            name='whatsapp_number',
            field=models.CharField(blank=True, help_text='WhatsApp only. The number with its country code, e.g. 977 9800000000. Fill this in and the link below is written for you.', max_length=24),
        ),
        migrations.AlterField(
            model_name='sociallink',
            name='href',
            field=models.URLField(blank=True, help_text='Full URL of the profile. Blank links stay hidden on the site.'),
        ),
        migrations.CreateModel(
            name='FooterLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first.')),
                ('is_published', models.BooleanField(default=True, help_text='Untick to hide from the site without deleting.')),
                ('label', models.CharField(max_length=40)),
                ('href', models.CharField(help_text='A path such as "/work".', max_length=120)),
                ('section', models.ForeignKey(blank=True, help_text='Set automatically; links are edited inside the section.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='links', to='content.footerbottomsection')),
            ],
            options={
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
    ]
