# Generated by Django 5.0.14 on 2026-09-26 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0011_footer_bottom_and_whatsapp_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='PopupSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=False, help_text='Nothing appears on the site until this is ticked.')),
                ('eyebrow', models.CharField(blank=True, default='Free guide', help_text='The small line above the heading.', max_length=60)),
                ('heading', models.CharField(default='Get more enquiries from your website.', max_length=120)),
                ('body', models.TextField(default='Practical tips on getting found online and turning visits into enquiries. No spam, unsubscribe any time.')),
                ('email_label', models.CharField(default='Your email address', max_length=60)),
                ('button_label', models.CharField(default='Subscribe', max_length=40)),
                ('success_message', models.CharField(default='Thanks — check your inbox soon.', max_length=160)),
                ('delay_seconds', models.PositiveSmallIntegerField(default=12, help_text='How long to wait before it appears. Showing it instantly annoys people and they leave.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'popup',
                'verbose_name_plural': 'popup',
            },
        ),
    ]
