# Generated by Django 5.0.14 on 2026-09-26 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0012_popupsection'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PopupSection',
        ),
    ]
