# Generated by Django 5.0.14 on 2026-10-01 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0013_delete_popupsection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='photo',
            field=models.URLField(blank=True, help_text='Cloudinary image URL. Paste your image URL here.'),
        ),
    ]
